config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'

  get 'main/index' => "main#index"
  get 'main/:id/mypage_student' => "main#mypage_student"
  get 'main/:id/mypage_teacher' => "main#mypage_teacher"

  get 'main/teacher_account_edit_confirm' => "main#teacher_account_edit_confirm"
  get 'main/student_account_edit/:id' => "main#student_account_edit"
  get 'main/student_account/:id' => "main#student_account"
  get 'main/student_faq' => "main#student_faq"

  get 'lessons/:id/new' => "lessons#new"
  get 'lessons/reserve' => "lessons#reserve"
  post 'lessons/update_reserve' => "lessons#update_reserve"
   
  get    '/login' => 'sessions#new'
  post   '/login_student' => 'sessions#create_student'
  post   '/login_teacher' => 'sessions#create_teacher'
  delete '/logout' => 'sessions#destroy'

  post    'favorites/:id/create' => 'favorites#create'
  post    'favorites/:id/destroy' => 'favorites#destroy'
  
  resources :users
  get 'users/:id/edit' => 'users#edit'
  post   'users/new' => 'users#new'
  post   'users/create2' => 'users#create2'
  root   'users#top'
 
  
  resources :teachers
  get   'teachers_top' => 'teachers#top'
  post  'teachers/new' => 'teachers#new'
  
  
  resources :lessons
  get 'lessons/:id/reserve' => "lessons#reserve"
  post 'lessons/create' => "lessons#create"
  post 'lessons/cancel' => "lessons#cancel"
  get 'lessons/:id/review' => 'lessons#review'
  post 'lessons/:id/review_write' => 'lessons#review_write'
  get 'lessons/:id/review_show' => "lessons#review_show"

end

app/models/user.rb
class User < ActiveRecord::Base
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    # before_save { self.email = email.downcase }
    attr_accessor :password_check


    validates :name, {presence: true ,uniqueness:true, length: { maximum: 25 }}
    # validates :skype, {presence: true }
    # validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX },length: { maximum: 255},uniqueness: { case_sensitive: false }}
    validates :email, {presence: true,length: { maximum: 50},uniqueness: { case_sensitive: false }}

    # validates :password, {presence: true }
    # validates_confirmation_of :password
  
    has_secure_password

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def top
    @user=User.new
  end
  def pass_forgot
  end
  def pass_forgot2
  end
  def new
    @user=User.new
  end
  def pre_login
  @user = User.new(
      name: params[:name],
      emails: params[:emails],
      password: params[:password]
    )
    if @user.save
      flash[:notice] = "ユーザー登録が完了しました。ログインしてください。"
      redirect_to("/user/top")
    else
        @error_message = "登録できませんでした。全ての項目を入力の上,アドレスが既に登録されていないかご確認ください。"
      render("user/new")
    end
  end
  
  def login
    @user = User.find_by(emails: params[:emails] ,password: params[:password])
    if @user 
      flash[:notice] = "ログインしました"
      session[:user_id]= @user.id
      redirect_to("/main/index")
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @emails = params[:emails]
      @password = params[:password]
      render("user/top")
    end
  
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :find_user, only: [:show, :edit, :update, :destroy]

  def top
      @user = User.new
  end
  
  def index #show all users
      @user = User.all
  end
  
  def show #show profile
    
  end

  def new #create registration form
      @user=User.new
      @user.teacher = false
  end
  
  # def new2 #create registration form
  #     @user=User.new
  #     @user.teacher = true
  # end

  def edit #edit profile
    @user = current_user
  end
  
  def create #save new user
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Your account is registered"
      redirect_to root_path
    else
      @error_message = "登録できませんでした。全ての項目を入力されていることを確認してください。"
      render 'new'
    end
  end
  
   
  def update #save edit profile
      #if password_current
        #if password_current != @user.password
            #@error_message = "type correct password first"
            #render :edit
        #elsif password != password_confirmation
            #@error_message = "new password and confirm password is not same"
            #render :edit
        #elsif @user.update(user_params)
            #flash[:notice] = "your account is editted"
           # redirect_to user_path
         # else
           # @error_message = "something wrong with the new password.try again"
        #    render :edit
        #  end
                        
      #  else
      #      @error_message = "couldn't edit. information of username and email birthday must be filled and have to be uniqe."
     #       render :edit
      #  end
                
    #  elsif password
    #    @error_message = "if you want to renew your password,type correct password first." 
     #   render :edit
     # elsif @user.update(user_params)
    #    flash[:notice] = "ユーザー情報を編集しました"
    #    redirect_to user_path
    #  else
    #    @error_message = "couldn't edit. information of username and email birthday must be filled and have to be uniqe."
     #   render :edit
     # end
   # end

    if !params[:user][:password].empty?
      if !@user.authenticate(params[:user][:password_check])
        @error_message = "wrong password"
        return render :edit
      end
    end
    
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を編集しました"
      redirect_to user_path
    else
      @error_message = "Failed to save changes."
      render :edit
    end
  
  end
  
  def destroy #delete user
  end
  
  
  private
    def find_user
      @user = User.find_by(id: params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email, :skype, :birthday,:sex, :teacher, :password,
                                   :password_confirmation)
    end
    
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    def correct_user
      @user = User.find_by(params[:id])
      if @user =! current_user
      flash[:notice] = "You are not allowed to access this page"
      redirect_to(root_url) 
      end
    end






=begin

  def top
    # @user=User.new
  end
  
  def email_authentication  
    @user = User.new(
      emails: params[:emails]
    )
    Usermailer.authentication_email(@user).deliver_now
    flash[:notice] = "A confirmation email has been sent to your email address. 
        Please click on the link in the email in order to activate your account."
    redirect_to("/user/top")
  end

  def pre_login
    @user = User.new(
      name: params[:name],
      sex: params[:sex],
      birthday_year: params[:birthday_year],
      birthday_month: params[:birthday_month],
      birthday_day: params[:birthday_day],
      skype: params[:skype],
      emails: params[:emails],
      password: params[:password]
    )
    password = params[:password]
    password_confirmation = params[:password2]
    if password != password_confirmation
        @error_message = "パスワードと確認用パスワードが一致しません。"
        render("users/new")
    elsif @user.save
      flash[:notice] = "ユーザー登録が完了しました。ログインしてください。"
      redirect_to("/user/top")
    else
        @error_message = "登録できませんでした。全ての項目を入力されていることを確認してください。"
      render("users/new")
    end
  end
  
    
    def account_edit 
        @user = User.find_by(id:params[:id])
        @user.name = params[:name]
        @user.emails = params[:emails]
        @user.sex = params[:sex]
        @user.birthday_year = params[:birthday_year]
        @user.birthday_month = params[:birthday_month]
        @user.birthday_day = params[:birthday_day]
        #@user.language= params[:language],
        #@user.hobby= params[:hobby],
        password_current = params[:password0]
        password = params[:password]
        password_confirmation = params[:password2]
        if password_current
                if password_current != @user.password
                    @error_message = "type correct password first"
                    render("main/student_account_edit")
                elsif password != password_confirmation
                    @error_message = "new password and confirm password is not same"
                    render("main/student_account_edit")
                elsif @user.save
                  @user.password = params[:password]
                    if @user.save
                        flash[:notice] = "ユーザー情報を編集しました"
                        redirect_to("/main/student_account/#{@user.id}")
                    else
                         @error_message = "something wrong with the new password.try again"
                         render("main/student_account_edit")
                    end
                    
                else
                  @error_message = "couldn't edit. information of username and email birthday must be filled and have to be uniqe."
                  render("main/student_account_edit")
                end
            
        elsif password
            @error_message = "if you want to renew your password,type correct password first." 
            render("main/student_account_edit")
        elsif @user.save
            flash[:notice] = "ユーザー情報を編集しました"
            redirect_to("/main/index/#{@user.id}")
        else
            @error_message = "couldn't edit. information of username and email birthday must be filled and have to be uniqe."
            render("main/student_account_edit")
        end
    end
=end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!--originally "student account edit.erb"-->
<% content_for :specific_css_js do %>
	 <%= stylesheet_link_tag "users/edit", :media => "all" %>
     <%= javascript_include_tag 'users/edit' %>
<% end %>
<!--main開始------------------------------------------------------------------------------------->   
	<%= form_for @user do |form| %>
		
		<!--<%#= form_tag("/user/account_edit/#{current_user.id}", {multipart: true}) do %>-->

		<div class="edit_profile_main">
			<div class="edit_profile_main_1">
			
				<p>edit your account</p>
						
			</div>
			
			 <div class="edit_profile_main_2">
			

					<div class="register name">
					
						<div class="register-left">
						  username
						</div>
						
						<div class="register-right">
							 <!--<input type="text"  class="input name" name="name" value="<%= current_user.name %>" >　-->
						    <%= form.text_field :name, class: 'input name'%>

						</div>
						
					</div>
					
					<div class="register mail">
					
						<div class="register-left">
							email address
						</div>
						
						<div class="register-right">

							 <!--<input type="text"  class="input name" name="emails" value="<%= current_user.email %>">-->
  						    <%= form.text_field :email, class: 'input name'%>
						</div>
						
					</div>
					
					<div class="register sex">

						<div class="register-left">
							sex
						</div>
						
						<div class="register-right">
							
							
							<!--<INPUT type="radio" name="sex" value="男性" checked>male&nbsp;&nbsp;&nbsp;&nbsp;-->
							<!--<INPUT type="radio" name="sex" value="女性" >female-->
							
							<%= form.radio_button :sex, 1, :checked => current_user.sex %>男性&nbsp;&nbsp;&nbsp;&nbsp
							<%= form.radio_button :sex, 0, :checked => !current_user.sex %>女性
						</div>
					
					</div>
					
					<div class="register birth">
					
						<div class="register-left">
							birthday
						</div>
						<div class="register-right">
						<!--<%= select_tag 'birthday_year', options_for_select(["1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990", "1991", "1992", "1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003"]),class:"select" %>year-->
						<!--<%= select_tag 'birthday_month', options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]),class:"select" %>month-->
						<!--<%= select_tag 'birthday_day', options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29","30"]),class:"select" %>day-->

						<%= form.date_field :birthday %>

						</div>
						
						
					</div>
					
					<!--<div class="register birth">
					
						<div class="register-left">
						  learning language
						</div>
						
						<div class="register-right">
							 <input type="text"  class="input name" name="language" value="<%= current_user.language %>">
						</div>
						
					</div>
					
					<div class="register birth">
					
						<div class="register-left">
						  hobby
						</div>
						
						<div class="register-right">
							 <input type="text"  class="input name" name="hobby" value="<%= current_user.hobby %>">
						</div>
						
					</div>-->
					
					<div class="register_password_change">
						if you want to chnage the password,fill the following boxes correctly
					</div>
					
					<div class="register birth">
					
						<div class="register-left">
							current password
						</div>
						
						<div class="register-right">
							 <!--<input type="password" name="password0"  class="input name">-->
  						    <%= form.text_field :password_check, class: 'input name'%>
						</div>
						
					</div>
					
					<div class="register birth">
					
						<div class="register-left">
							new password
						</div>
						
						<div class="register-right">
							 <input type="password" name="password"  class="input name">
   						    <%= form.text_field :password, class: 'input name'%>
						</div>
						
					</div>

					
					<div class="register birth">
					
						<div class="register-left">
							confirm password 
						</div>
						
						<div class="register-right">
							 <!--<input type="password" name="password2"  class="input name">-->
  						    <%= form.text_field :password_confirmation, class: 'input name'%>
						</div>
						
					</div>
				
        			</div>
        			<br>
        			<div class="edit_profile_main_3">
        			
        			<input class="btn1" type="submit" value="edit your account">
        			</div>
        			</br>
			<% end %>

		</div>
<!--トップに戻る開始----------------------------------------------------------------------------->
		
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>
<!--トップに戻る終了（共通：変えないこと）------------------------------------------------------>
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer id="footer">
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      
      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->
		<!--<script src="teacher_edit_account.js"></script>-->

app/views/users/edit_info.html.erb
<% content_for :specific_css_js do %>

<% end %>

	<% if @error_message %>
		<header2>
            <div class="form-error">
                <%= @error_message %>
            </div>
        </header2>
    <% end %>

	<div class="inputbox">
		
		<%= form_for @user, url: user_edit_info_path do |f| %>
		  Name:<%= f.text_field :name, placeholder: @user.name%>
		  Email:<%= f.text_field :emails, placeholder: @user.emails%>
          Password:<%= f.password_field :password %>
          Password(Confirmation):<%= f.password_field :password_confirmation %>
		  <%= f.submit "Save Edit"%>
		<% end %>
		
	</div>

app/views/users/index.html.erb
<!--show all users-->

app/views/users/new.html.erb
<% content_for :specific_css_js do %>
		<%= stylesheet_link_tag "users/new", :media => "all" %>
<% end %>

<!--入力画面開始----------------------------------------------------------------------------------------->   
	<% if @error_message %>
	  <header2>
          <div class="form-error">
            <%= @error_message %>
          </div>
      </header2>
    <% end %>
	
	<div class="signup_main">
		<div class="signup_main_1">
			<p>Register account information as a student</p>
		</div>
		
		<div class="signup_main_2">
			<div class="signup_main_2_right">
					<a class="btn facebook">
						<span class="fa fa-facebook"></span>
						facebookを使って登録
					</a>
					
					<a class="btn twitter">
						<span class="fa fa-twitter"></span>
						twitterを使って登録
					</a>
					
					<p class="explain">facebookやtwitterアカウントを使うと、メールアドレス・生年月日・性別の入力が簡単になります。</p>
			</div>
			
	<%= form_for @user do |form| %>
				<div class="signup_main_2_left">
					
					<div class="register name">
						<div class="register-left">
							username
						</div>
						<div class="register-right">
						    <!--<input type="name" name="name"  class="input name" value="<%= @user.name %>">-->
						    <%= form.text_field :name, class: 'input name'%>
						</div>
					</div>
					
					<div class="register sex">
						<div class="register-left">
							sex
						</div>
						<div class="register-right">
							<%= form.radio_button :sex, 1, :checked => true %>男性&nbsp;&nbsp;&nbsp;&nbsp
							<%= form.radio_button :sex, 0 %>女性

							<!--<INPUT type="radio" name="sex" value="男性" checked>男性&nbsp;&nbsp;&nbsp;&nbsp;-->
							<!--<INPUT type="radio" name="sex" value="女性" >女性-->
						</div>
					</div>
					
					<div class="register birth">
						<div class="register-left">
							生年月日
						</div>
						<div class="register-right" name="birthday">
							<%= form.date_field :birthday %>

						  <!--<%= select_tag 'birthday_year', options_for_select(["1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990", "1991", "1992", "1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003"]),class:"select" %>年-->
						  <!--<%= select_tag 'birthday_month', options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]),class:"select" %>月-->
						  <!--<%= select_tag 'birthday_day', options_for_select(["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29","30"]),class:"select" %>日-->
							
						</div>
					</div>
					
					<div class="register skype">
						<div class="register-left">
							Skype ID
						</div>
						<div class="register-right">
 						    <%= form.text_field :skype, class: 'input id'%>
							 <!--<input type="skype" name="skype"  class="input id" value="<%= @user.skype %>" >-->
						</div>
					</div>
					
					<div class="register email">
						<div class="register-left">
							Email 
						</div>
						<div class="register-right">
							 <!--<input type="email" name="email"  class="input id" value="<%= @user.email %>" >-->
 						    <%= form.text_field :email, class: 'input id'%>
						</div>
					</div>
					
					<div class="register birth">
						<div class="register-left">
							パスワード
						</div>
						<div class="register-right">
							 <!--<input type="password" name="password"  class="input name">-->
 						    <%= form.text_field :password, class: 'input name'%>

						</div>
					</div>
					
					<div class="register birth">
						<div class="register-left">
							パスワード（確認）
						</div>
						<div class="register-right">
							 <!--<input type="password" name="password2"  class="input name">-->
 						    <%= form.text_field :password_confirmation, class: 'input name'%>

						</div>
					</div>
					
					<div class="signup_main_3">
					   <p class="explain2"><a class="contract"  href="#">ganjin利用規約</a>を一読の上、同意される方のみ「同意して確認画面へ進む」ボタンを押してください。</p>
			           <!--<input class="btn1"type="submit" value="同意して確認画面へ進む">-->
			            <%= form.submit "同意して確認画面へ進む", class: 'btn1' %>
		            </div>
				</div>
			<% end %>
		</div>
			
	</div>
		
<!--入力画面終了----------------------------------------------------------------------------------------->   
	

app/views/users/show.html.erb
<!--originally "student account.erb"-->
<% content_for :specific_css_js do %>
	<%= stylesheet_link_tag "users/show", :media => "all" %>     
	<%= javascript_include_tag 'users/show' %>
<% end %>
         <!--完了モーダル開始------------------------------------------------------>   

        	<div class="complete-modal-wrapper" id="complete-modal">
    			<div class="modal">
    				 <div class="close-modal">
        				<i class="fa fa-2x fa-times"></i>
      			     </div>
      				
      				 <div id="complete-form">
        				<h2 class="sentence">正常にアカウント情報を変更しました。</h2>
        				<form action="#">
          					
          					<a id="submit-btn2"  href="#">トップに戻る</a>
       					 </form>
      				</div>
    			</div>
			</div>

        <!--完了モーダル終了------------------------------------------------------>  
        
<!--ヘッダー終了（共通：変えないこと）--------------------------------------------------->   
<!--main開始------------------------------------------------------------------------------------->   
		
		<div class="edit_account_main_confirm">
			<div class="edit_account_main_confirm_1">
			
				<p>your account information</p>
						
			</div>
			
			<div class="edit_account_main_confirm_2">
			

					<div class="register name">
					
						<div class="register-left">
							name
						</div>
						
						<div class="register-right">
							<div  class="input2 name"><%= current_user.name%></div>
						</div>
						
					</div>
					
					<div class="register mail">
					
						<div class="register-left">
							email
						</div>
						
						<div class="register-right">
							 <div class="input name"><%= current_user.email%></div>
						</div>
						
					</div>		
					
					<div class="register sex">
					
						<div class="register-left">
							sex
						</div>
						

						<div class="register-right">
							
							
							<div>
							<% if current_user.sex %>
							 male
							<% else %>
							 female
							<% end%>
							</div>

						</div>
					
					</div>
					
					<div class="register birth">
					
						<div class="register-left">
							birthday
						</div>
						
						<div class="register-right">
							
                            <div><%= current_user.birthday%></div>
                       
						
					    </div>
					
	
			</div>
			<br>
			<div class="edit_account_main_confirm_3">
			
			
			<!--<input class="btn1" value="アカウント情報を変更する" id="complete-show">-->
			<!--<%= link_to("edit your account","/main/student_account_edit/#{current_user.id}" ,class:"btn1") %>-->
   	       	<%= link_to("edit your account",edit_user_path(current_user),class:"btn1") %>

			</div>
		</div>
    </div>
<!--トップに戻る開始----------------------------------------------------------------------------->
		
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>

<!--トップに戻る終了（共通：変えないこと）------------------------------------------------------>
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer id="footer">
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      

      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->

		<!--<script src="teacher_edit_account.js"></script>-->
    
    

app/views/users/top.html.erb
<% content_for :specific_css_js do %>
	<%= stylesheet_link_tag "users/top", :media => "all" %>
    <%= javascript_include_tag 'users/top' %>
<% end %>
   
<!--トップ開始-------------------------------------------------------------------------------->
		
	<div class="top-wrapper-1">
		<div class="container">
		
			<h1>Learn Japanese</h1>
			
			<div class="btn-wrapper">
				<a class="btn log-in" id="login-show-student">Login</a>
			</div>
			<div class="btn-wrapper">
				<a class="btn sign-up" id="signup-show-student">Sign up</a>
			
				
				<!--<p>or sign up with</p>
				
				<a class="btn facebook">
					<span class="fa fa-facebook"></span>facebook
				</a>
				
				<a class="btn twitter">
				<span class="fa fa-twitter"></span>twitter
				</a>-->
			</div>
		</div>
	</div>
	
	<!--<div class="top-wrapper-2">-->
	<!--	<div class="container">-->
		
	<!--		<h1>Teach Japanese</h1>-->
			
	<!--		<div class="btn-wrapper">-->
	<!--			<a class="btn login" id="login-show-teacher">Login</a>-->
	<!--		</div>-->
	<!--		<div class="btn-wrapper">-->
	<!--			<a class="btn sign-up" id="signup-show-teacher">Sign up</a>-->
				
				<!--<p>or sign up with</p>
				
	<!--			<a class="btn facebook">-->
	<!--				<span class="fa fa-facebook"></span>facebook-->
	<!--			</a>-->
				
	<!--			<a class="btn twitter">-->
	<!--			<span class="fa fa-twitter"></span>twitter-->
	<!--			</a>-->-->
	<!--		</div>-->
	<!--	</div>-->
	<!--</div>-->
<!--トップ終了-------------------------------------------------------------------------------->	

<!--生徒サインアップモーダル開始---------------------------------------------------->
	<div class="signup-model-wrapper" id="signup-model-student">
		<div class="model">
			<div class="close-model">
    			<i class="fa fa-2x fa-times"></i>
  			</div>
  				
  			<div id="signup-form">
				<h2>新規登録</h2>
				<p class="subtitle">ご入力頂くEメールアドレスに新規登録用のURLをお送り致します。</p>
				
				<%= form_for @user ,url: new_user_path do |form| %>
	  				<%= form.text_field :email,{ class:"form-control", placeholder: "メールアドレス"} %>
 					<%= form.submit "メール送信", class:"submit-btn"%>
				<% end %>

				
				<%#= form_tag(new_user_path, method: "post") do %>
  					<%#= text_field_tag :email,nil,{ class:"form-control", placeholder: "メールアドレス"} %>
  					<%#= submit_tag "メール送信", class:"submit-btn"%>
				<%# end %>
				
  			</div>
		</div>
	</div>
<!--生徒サインアップモーダル終了---------------------------------------------------->	

<!--student ログインモーダル開始------------------------------------------------------>   
<div class="login-model-wrapper" id="login-model-student">
	<!-- ログインのモーダル部分のHTMLを貼り付けてください -->
	<div class="model">
	 	<div class="close-model">
			<i class="fa fa-2x fa-times"></i>
  		</div>
  	
  		<div id="login-form">
			<h2>studentログイン</h2>
			
			<!--<%#= form_for(:session, url: login_student_path) do |f| %>-->
		 <!--   	<%#= f.email_field :email, {class: "form-control",placeholder:"メールアドレス"}%>-->
		 <!--     	<%#= f.password_field :password, {class: "form-control", placeholder:"パスワード"} %>-->
			<!--	<div class="idpass-forget"> -->
  	<!--				<%#= link_to("IDまたはパスワードを忘れた方はこちら","/user/pass_forgot" ,class:"idpass-forget") %>-->
  	<!--			</div>-->
		 <!--     	<%#= f.submit "ログイン", class:"submit-btn" %>-->
   <!--			<%# end %>-->
   			
   			<%= form_tag(login_student_path, method: "post") do %>
  				<%= text_field_tag :email,nil,{ class:"form-control", placeholder: "メールアドレス"} %>
				<%= password_field_tag :password,nil,{ class:"form-control", placeholder: "パスワード"} %>
				<div class="idpass-forget"> 
  					<%= link_to("IDまたはパスワードを忘れた方はこちら","/user/pass_forgot" ,class:"idpass-forget") %>
  				</div>
  				<%= submit_tag "ログイン", class:"submit-btn"%>
			<% end %>
			
  		</div>
	</div>
</div>

	<div class="lesson-wrapper"></div>
	<div class="message-wrapper"></div>
	
	<footer></footer>