config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'

  get 'main/index' => "main#index"
  get 'main/:id/mypage_student' => "main#mypage_student"
  get 'main/:id/mypage_teacher' => "main#mypage_teacher"

  get 'main/teacher_account_edit_confirm' => "main#teacher_account_edit_confirm"
  get 'main/student_account_edit/:id' => "main#student_account_edit"
  get 'main/student_account/:id' => "main#student_account"
  get 'main/student_faq' => "main#student_faq"

  get 'lessons/:id/new' => "lessons#new"
  get 'lessons/reserve' => "lessons#reserve"
  post 'lessons/update_reserve' => "lessons#update_reserve"
   
  get    '/login' => 'sessions#new'
  post   '/login_student' => 'sessions#create_student'
  post   '/login_teacher' => 'sessions#create_teacher'
  delete '/logout' => 'sessions#destroy'

  post    'favorites/:id/create' => 'favorites#create'
  post    'favorites/:id/destroy' => 'favorites#destroy'
  
  resources :users
  get 'users/:id/edit' => 'users#edit'
  post   'users/new' => 'users#new'
  post   'users/create2' => 'users#create2'
  root   'users#top'
 
  
  resources :teachers
  get   'teachers_top' => 'teachers#top'
  post  'teachers/new' => 'teachers#new'
  
  
  resources :lessons
  get 'lessons/:id/reserve' => "lessons#reserve"
  post 'lessons/create' => "lessons#create"
  post 'lessons/cancel' => "lessons#cancel"
  get 'lessons/:id/review' => 'lessons#review'
  post 'lessons/:id/review_write' => 'lessons#review_write'
  get 'lessons/:id/review_show' => "lessons#review_show"

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base


  
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
 before_action :logged_in_user, only: [:edit, :update]
 before_action :correct_user,   only: [:edit, :update]

  def index
  end
  
  def new  
    @lesson = Lesson.new
  end
 
  
  def create  #make a new reservation
    #shedule = params[:time]
    #times = params[:time].inspect
    #count = times.length

     #(0..count).each do |num|
    
    #Rails.logger.debug("ayayayayyayayayayyayayayyayayayayayyayayaya")
    time = params[:time]
    Lesson.where(teacher_id: current_user).where(condition:3).destroy_all
    if time
        Rails.logger.debug(time)
        iteration = time.length-1

        (0..iteration).each do |ite|
            @lesson = Lesson.new
            unless time.nil?
                @lesson.time = DateTime.parse(time[ite].to_s)
                @lesson.date = Date.parse(time[ite].to_s)
                #@lesson.date = DateTime.parse(time[ite].days.to_s)
            end
            @lesson.teacher_id = current_user.id
            @lesson.condition= 3
            @lesson.save
            #time: params[:time],
                                # teacher_id: current_user.id,
                                # date: params[:date],
                                # condition: 3 )              # 1:done , 2:reserved, 3:available
            Rails.logger.debug(@lesson)
            Rails.logger.debug(iteration)
        end
        redirect_to("/main/#{current_user.id}/mypage_teacher")
     else
     @error_message = "登録できませんでした。全ての項目を入力されていることを確認してください。"
      render 'lessons/new'
    end
  end
  
  def reserve
     
    @teacher = Teacher.find_by(id: params[:id])
    @time= params[:time]
    @lesson = Lesson.find_by(id: params[:lid])
    
  end
  
    def update_reserve
    @lesson = Lesson.find_by(id: params[:lesson_id])
    @lesson.user_id= current_user.id
    @lesson.condition= 2
    @lesson.Japanese_skill = params[:japanese_skill].to_s

    
    if @lesson.save
      
      redirect_to("/main/#{current_user.id}/mypage_student")
    else
      @error_message = "登録できませんでした。全ての項目を入力されていることを確認してください。"
      render 'lessons/new'
    end
    
    
  end
  
  def update
  
  end
 
 
 def cancel
  lesson = Lesson.find_by(id: params[:id])
  lesson.condition = 3
  lesson.user_id = nil
  lesson.Japanese_skill = nil
  lesson.save
  
  redirect_to("/main/mypage_student")
  
  end


  def review
    @lesson = Lesson.find_by(id: params[:id])
    @teacher = Teacher.find_by(id: @lesson.teacher_id)
    @count_done =Lesson.where(user_id: current_user.id ).where(condition:1).where(teacher_id: @teacher.id).length
    
  end
  
  def review_write
    @lesson = Lesson.find_by(id: params[:id])
    
    @lesson.review_comment = params[:review_comment].to_s

    @lesson.review_rate = params[:review_rate].to_i
  
    @lesson.save
    
    teacher = Teacher.find_by(id: @lesson.teacher_id)
    lesson_teachers = Lesson.where(teacher_id: teacher.id).where(condition: 1)
    count_lesson= Lesson.where(teacher_id: teacher.id).where(condition: 1).length
    
    teacher_rate_sum = 0
    
   lesson_teachers[0..count_lesson].each do |lesson_teacher|
    
    teacher_rate_sum = teacher_rate_sum.to_f + lesson_teacher.review_rate.to_f
        
   end
   
   teacher.rate = (teacher_rate_sum / count_lesson).to_f
  
   teacher.num = count_lesson  
   teacher.save
    
    redirect_to("/main/mypage_student")
    
  end
  
  def review_show
    @lessons = Lesson.where(teacher_id: params[:id]).where(condition: 1)
    @lessons_count = Lesson.where(teacher_id: params[:id]).where(condition: 1).length
  end
  
  
  private
      def lesson_params
        params.require(:lesson).permit(time: [])
      end
 
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/new.html.erb
<% content_for :specific_css_js do %>
		<%= stylesheet_link_tag "lessons/new", :media => "all" %>
		<%= javascript_include_tag 'lessons/new' %>
<% end %>

<div class="main">
<div class="schedule">
					<p class="schedule-title">
						SCHEDULE &nbsp;&nbsp;&nbsp;&nbsp; (授業可能な日時・時間帯にチェックを入れて確定。)
					</p>
					<div class="schedule-timeselect">
					
								
					</div>
		<%= form_tag(lessons_create_path, method: "post") do %>
					<div class="schedule-table">
						<table class="table-schedule"  style="border-color:rgba(34, 49, 52, 0.3)" rules="all">
  								
  								<tr>
    								<td class="title-schedule-left lefttop"></td>
    								<% today = Date.today %> 
    								<% baseday = today.day.to_i%>
    								<% basetime = today.midnight%>
    								
    								<% (0..6).each do |num|%>
    								<td class="title-schedule"><%=baseday+num%></td>          <!--月の変わり目注意-->
    								<% end %>
    	
  								</tr>
  								
  								<tr class="time1">
  								    <% (0..47).each do |num|%>
  								    <% start_time = basetime + num * 30.minutes %>
  								    <% end_time = start_time + 30.minutes %>
  								    
  								    
  								    <% if start_time.min == 30 %>
    								    <td class="title-schedule-left"><%=start_time.hour%>:<%="%02d" % start_time.min%>-<%=end_time.hour%>:<%="%02d" % end_time.min%></td>
    				                <%else%>
    				                    <td class="schedule-row-color"><%=start_time.hour%>:<%="%02d" % start_time.min%>-<%=end_time.hour%>:<%="%02d" % end_time.min%></td>
    	                            <%end%>
    				                <% (0..6).each do |day|%>
                
                                     <% lesson_time = start_time + day * 1.days %>                      <!--月の変わり目注意 対策考えること-->
                
                                    <% if start_time.min == 30 %>
        								<td class="title-schedule-left">
        								    <%if DateTime.now < lesson_time %>
    
            								    <%# if @lesson = Lesson.find_by(time:lesson_time) %>
                                                <% if @lesson = Lesson.where(time:lesson_time).where(teacher_id:current_user).first %>
            								       
            								        <%case @lesson.condition %> 
            								        <%when 1%>
            								            <p class="reserved">done </p>
            								        <%when 2%>
            								            <p class="reserved">reserved </p>
            								        <%when 3%>
            								            <%= check_box_tag 'time[]', lesson_time , id='checked'%>
            								        <% end%>
            								    <% else %>
            								        <%= check_box_tag 'time[]', lesson_time %>
            								    <% end%>
            								<%end%>
            								    
        								</td>
                                    <%else%>
                                        <td class="schedule-row-color">
                                            <%if DateTime.now < lesson_time %>
                                                <%# if @lesson = Lesson.find_by(time:lesson_time) %>
                                                <% if @lesson = Lesson.where(time:lesson_time).where(teacher_id:current_user).first %>
            								    
            								        <%case @lesson.condition %> 
                								        <%when 1%>
                								            <p class="reserved">done </p>
                								        <%when 2%>
                								            <p class="reserved">reserved </p>
                								        <%when 3%>
                								            <%= check_box_tag 'time[]', lesson_time , id='checked'%>
                								        <% end%>
            								    <% else %>
            								        <%= check_box_tag 'time[]', lesson_time %>
            								    <% end%>
            								  <% end%>
                                        </td>
                                    <% end %>
                                    
                                    <% end %>
    								
    							   			
    							   			
  								</tr>
  								 						
  								<% end %>
  															  								
  				
  								  								  								
							</table>
							<%= submit_tag "予定を設定する", class: 'btn1' %>
							
							<div id="review"></div> <!--マーキング-->
					</div>		
		          <% end %>
				</div>

</div>

<!--トップに戻る開始------------------------------------------------------------------------->
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>
<!--トップに戻る開始------------------------------------------------------------------------->
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer>
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      
      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->

app/views/lessons/new3.html.erb
<% content_for :specific_css_js do %>
		<%= stylesheet_link_tag "lessons/new", :media => "all" %>
		<%= javascript_include_tag 'lessons/new' %>
<% end %>


<!--入力画面開始-----------------------------------------------------------------------------------------> 
<%= form_tag("/lessons/create") do %>
<div class="main">
   <h1 class="title">Make a reservation for your lesson.</h1> 
        <p class="subtitle">Your lesson is shown below, confirm your lesson if there are no problems.</p>
<hr size="1px">
    <div class="main-left">
         <img class="Profile-photo" src="<%="/conversation.jpg"%>"><br>
      	<%= @teacher.name %><br>
      	1 lesson:<%= @teacher.cost %> $<br>
      	★★★★★<br>
      	hobby:<%= @teacher.hobby %>
      	
    </div>

    <div class="main-right">
    <% require "time" %>
    <% t= Time.parse("#{@time}"); %>
    <% if t.min==0 %>
      <% min1 = "00" %>
      <% min2 = 30 %>
      <% hour2 = t.hour %>
    <% else %>
      <% min1 = "30" %>
      <% min2 = "00" %>
      <% hour2 = t.hour+1 %>
    <% end %> 
    
    <% time = t.hour+t.min+t.sec %>  
   
    <p><%= t.year %>.<%= t.month %>.<%= t.day %> <%= t.hour %>:<%= min1 %> - <%= hour2 %>:<%= min2 %></p>
    <span class="ability">Tell your Japanese ability to your teacher in advance</span>
    
    <textarea class="text" name="japanese_skill"><%= @lesson.Japanese_skill %></textarea>
    
    <!--情報飛ばす用開始（ほかにいい案があれば変更のこと）---------------------------------------------------->
     <textarea class="invisible" name="teacher_id"><%= @teacher.id %></textarea>
     <textarea class="invisible" name="time"><%= t %></textarea>
     <textarea class="invisible" name="date"><%= t %></textarea>
     <!--情報飛ばす用終了（ほかにいい案があれば変更のこと）---------------------------------------------------->
     
     <input type="submit" value="make a reservation" class="btn1">
    
    </div>
  <% end %> 
<!--予約確認用モーダル開始---------------------------------------------------->

<!--予約確認用モーダル終了---------------------------------------------------->
	
</div>

<!--トップに戻る開始------------------------------------------------------------------------->
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>
<!--トップに戻る開始------------------------------------------------------------------------->
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer>
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      
      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->

app/views/lessons/reserve.html.erb
<% content_for :specific_css_js do %>
		<%= stylesheet_link_tag "lessons/reserve", :media => "all" %>
		<%= javascript_include_tag 'lessons/reserve' %>
<% end %>


<!--入力画面開始-----------------------------------------------------------------------------------------> 
<%= form_tag("/lessons/update_reserve") do %>
<div class="main">
   <h1 class="title">Make a reservation for your lesson.</h1> 
        <p class="subtitle">Your lesson is shown below, confirm your lesson if there are no problems.</p>
<hr size="1px">
    <div class="main-left">
         <img class="Profile-photo" src="<%="/conversation.jpg"%>"><br>
      	<%= @teacher.name %><br>
      	1 lesson:<%= @teacher.cost %> $<br>
      	★★★★★<br>
      	hobby:<%= @teacher.hobby %>
      	
    </div>

    <div class="main-right">
    <% require "time" %>
    <% t= Time.parse("#{@time}"); %>
    <% if t.min==0 %>
      <% min1 = "00" %>
      <% min2 = 30 %>
      <% hour2 = t.hour %>
    <% else %>
      <% min1 = "30" %>
      <% min2 = "00" %>
      <% hour2 = t.hour+1 %>
    <% end %> 
    
    <% m = t.month.to_i %>
      <% if m < 10 %>
                  <% m = "0" + m.to_s %>
                <% else %>
                  <% m = m.to_s %>                      
                <%end%>
    <% h = t.hour.to_i %>
                <% if h < 10 %>
                  <% h = "0" + t.hour.to_s %>
                <% else %>
                  <% h = t.hour.to_s %>
                <%end%>
         <% s = "00" %>
    <% time = t.hour+t.min+t.sec %>  
    
    <% t1 = t.year.to_s + "-" + m + "-" + t.day.to_s + " " + h  + ":" + min1  + ":" + s; %>
    
    <p><%= t.year %>.<%= t.month %>.<%= t.day %> <%= t.hour %>:<%= min1 %> - <%= hour2 %>:<%= min2 %></p>
    <span class="ability">Tell your Japanese ability to your teacher in advance</span>
    
    <textarea class="text" name="japanese_skill"></textarea>
    
    <!--情報飛ばす用開始（ほかにいい案があれば変更のこと）---------------------------------------------------->
     <textarea class="invisible" name="teacher_id"><%= @teacher.id %></textarea>
     <textarea class="invisible" name="time"><%= t1.to_s %></textarea>
     <textarea class="invisible" name="date"><%= @time %></textarea>
     <textarea class="invisible" name="lesson_id"><%= @lesson.id %></textarea>
     <!--情報飛ばす用終了（ほかにいい案があれば変更のこと）---------------------------------------------------->
     
     <input type="submit" value="make a reservation" class="btn1">
    
    </div>
  <% end %> 
<!--予約確認用モーダル開始---------------------------------------------------->

<!--予約確認用モーダル終了---------------------------------------------------->
	
</div>

<!--トップに戻る開始------------------------------------------------------------------------->
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>
<!--トップに戻る開始------------------------------------------------------------------------->
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer>
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      
      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->

app/views/lessons/review.html.erb
<!--originally "student account edit.erb"-->
<% content_for :specific_css_js do %>
	 <%= stylesheet_link_tag "lessons/review", :media => "all" %>
     <%= javascript_include_tag 'lessons/review' %>
     <%= javascript_include_tag 'jquery.raty' %> 
<% end %>
<!--main開始------------------------------------------------------------------------------------->   
	
	<%= form_tag("/lessons/#{@lesson.id}/review_write") do %>
	<div class="student_write_review_main">
			<div class="student_write_review_main_1">
			
				<p>Write a review about this teacher</p>
						
			</div>
			
			<div class="student_write_review_main_2">
			
                <div class="student_write_review_main_2_left">
					<img class="Profile-photo-teacher" src="profile_pic_temp.png" >
				</div>
						
				<div class="student_write_review_main_2_center">
					<p class="teacher-name"><%= @teacher.name %></p>
					<p class="date"><%= @lesson.date %></p>
					<p class="hour">0.5 hour</p>
					<p class="note">You have taken this teacher's class <span class="class-times"><%= @count_done %></span> times</p>					
				</div>
						
								
			</div>
			
           
            <table class="student_write_review_main_3" rules="all">
                <tr>
                    <td class="table-left">Rating</td>
                    <td class="table-right">
                        
                       <div id="star_rank" class = "star"></div><div id="hint" class = "rate"></div>
                        <%= hidden_field_tag :review_rate, @lesson.review_rate %>


                        <!--<p class="rating-pointer-1">required</p><p class="rating-pointer-2">OK</p>    必須入力項目の入力有無確認用にのやつ <td class="table-left">Rating</td>のratingの左に入れる -->

                       <!-- <p class="star-1">★</p> 
                        <p class="star-2">★</p>
                        <p class="star-3">★</p>
                        <p class="star-4">★</p>
                        <p class="star-5">★</p>  -->
                        
                        <!--<p class="rating">Click the star and rate this teacher</p>
                        <p class="rating-1">Disgusting</p>
                        <p class="rating-2">unsatisfied</p>
                        <p class="rating-3">Normal</p>
                        <p class="rating-4">Satisfied</p>
                        <p class="rating-5">Wanna have sex with</p>-->
                    </td>
                </tr>
                <tr>
                    <td class="table-left">Comment</td>
                    <td class="table-right">
                    <textarea name="review_comment" class="review_honbun" placeholder="Write your review here. How did you feel with this teacher's lesson?" ><%= @lesson.review_comment %></textarea>
                    
                    <p class="count-words" id="inputlength">0文字</p>
                    </td>
                </tr>
                
            </table>
            
             <input type="submit" value="Submit" class="input3">
            
		</div>
		
		<% end %>
<!--トップに戻る開始----------------------------------------------------------------------------->
		
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>
<!--トップに戻る終了（共通：変えないこと）------------------------------------------------------>
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer id="footer">
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      
      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->
<script type="text/javascript">
 
  $(function(){
    $('#star_rank').raty({
     
      size     : 100,
      starOff  : '<%= asset_path('star-off.png') %>',
      starOn   : '<%= asset_path('star-on.png') %>',
      target    : '#hint',
      targetType: 'number',
      targetKeep: true,
    click: function(score, evt) {
//	      alert('ID: ' + $(this).attr('id') + "\nscore: " + score + "\nevent: " + evt); //選択時に要素をアラート
      $("#review_rate").val(score);
    }
  });
  });
 
  </script>

app/views/lessons/review_show.html.erb
<% content_for :specific_css_js do %>
		<%= stylesheet_link_tag "lessons/review_show", :media => "all" %>
		<%= javascript_include_tag 'lessons/review_show' %>
<% end %>


<!--メイン画面開始-----------------------------------------------------------------------------------------> 
<div class="review">
					<p class="reviw-title">
						REVIEWS
					</p>
					
					<hr>
					<% if @lessons_count >= 1 %>
					
				  <% @lessons.each do |lesson| %>
				   
				    <% user = User.find_by(id: lesson.user_id) %>
					<div class="each-review">
						<div class="each-review-left">
							<img class="students-profile-photo" src="profile_pic_temp.png">
							
						</div>
						
						<div class="each-review-right1">
							<span class="students-evaluation"><% if lesson.review_rate == 5 %>
							     ★★★★★
							 <% elsif lesson.review_rate == 4 %> 
							     ★★★★☆
							 <% elsif lesson.review_rate == 3 %>
							     ★★★☆☆
							 <% elsif lesson.review_rate == 2 %>
							     ★★☆☆☆
							 <% elsif lesson.review_rate == 1 %>
							     ★☆☆☆☆
							 <% end %>	
							 (&nbsp;<%= lesson.review_rate %>&nbsp;)<br>	
							 </span>	
							 by	<span class="students-name"> <%= user.name %> </span>
							
						</div>	
						
						<div class="each-review-right2">
							Took the class at <%= lesson.time.year %>.<%= lesson.time.month %>.<%= lesson.time.day %>
							
						</div>	
						
						<div class="each-review-right3">
							<br><br><%= lesson.review_comment %>
							
						</div>						
					
					</div>
				<% end %>										
								
					
				  
				  
				 
				
					
					<!--<div class="read-more">-----> 
					<!--	Read more reviews-----> 
					<!--</div>-----> 
					
				<% else %>
				<div class="no-review">
				    &nbsp;&nbsp;&nbsp;no reviews are written for this teacher yet.
				</div>
				<% end %>
				</div>
				<!--レビュー終了-----------------------------------------------------------------> 



<!--メイン画面終了-----------------------------------------------------------------------------------------> 
<!--予約確認用モーダル開始---------------------------------------------------->

<!--予約確認用モーダル終了---------------------------------------------------->
	


<!--トップに戻る開始------------------------------------------------------------------------->
		<div class="back-to-top">
		
			<a class="back-to-top-word" href="#">Back to top</a>
		
		</div>
<!--トップに戻る開始------------------------------------------------------------------------->
<!-- フッター開始（共通：変えないこと）--------------------------------------------------------->
         <footer>
      		
      		<div class="footer-logo">
       			 Progate
      		</div>
      
      		<div class="footer-list">
        		<ul>
          			<li>会社概要</li>
          			<li>採用</li>
          			<li>お問い合わせ</li>
        		</ul>
      		</div>
    	</footer>
    	
<!-- フッター終了（共通：変えないこと）--------------------------------------------------------->