config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'

  get 'main/index' => "main#index"
  get 'main/:id/mypage_student' => "main#mypage_student"
  get 'main/:id/mypage_teacher' => "main#mypage_teacher"

  get 'main/teacher_account_edit_confirm' => "main#teacher_account_edit_confirm"
  get 'main/student_account_edit/:id' => "main#student_account_edit"
  get 'main/student_account/:id' => "main#student_account"
  get 'main/student_faq' => "main#student_faq"

  get 'lessons/:id/new' => "lessons#new"
  get 'lessons/reserve' => "lessons#reserve"
  post 'lessons/update_reserve' => "lessons#update_reserve"
   
  get    '/login' => 'sessions#new'
  post   '/login_student' => 'sessions#create_student'
  post   '/login_teacher' => 'sessions#create_teacher'
  delete '/logout' => 'sessions#destroy'

  post    'favorites/:id/create' => 'favorites#create'
  post    'favorites/:id/destroy' => 'favorites#destroy'
  
  resources :users
  get 'users/:id/edit' => 'users#edit'
  post   'users/new' => 'users#new'
  post   'users/create2' => 'users#create2'
  root   'users#top'
 
  
  resources :teachers
  get   'teachers_top' => 'teachers#top'
  post  'teachers/new' => 'teachers#new'
  
  
  resources :lessons
  get 'lessons/:id/reserve' => "lessons#reserve"
  post 'lessons/create' => "lessons#create"
  post 'lessons/cancel' => "lessons#cancel"
  get 'lessons/:id/review' => 'lessons#review'
  post 'lessons/:id/review_write' => 'lessons#review_write'
  get 'lessons/:id/review_show' => "lessons#review_show"

end

app/views/layouts/_navbar.html.erb
<header>
    <% if logged_in? %>
            <div class="container">
                <div class="header-left">
            
                    <%= link_to image_tag("https://prog-8.com/images/html/advanced/main_logo.png",:class => 'logo'),
                            {action: 'index', controller: 'main'},{class:'logout'}%>
                    <div class="search_user">
                        <input type="text" id="user" placeholder="Username" class="input1">
                        <!--- <%= submit_tag '検索' %>
                        <%= text_field_tag :keywd,'',size:30 %> -->

                        <!--<span class="fa fa-search"></span>-->
                        
                    </div>
                </div>
                
                 <div class="header-right">
                
                	<ul id="normal" class="dropmenu"> 
						<li><a><span class="fa fa-cog"></a>
  					 		 <ul>
   							   <!--<li><%= link_to("account","/main/student_account/#{current_user.id}") %></li>-->
     					       <li><%if session[:teacher]%>
     					       <%= link_to("acount",teacher_path(current_user)) %>
     					       <%else%>
     					       <%= link_to("account",user_path(current_user)) %>
     					       <%end%>
     					       </li>
    					       <!--<li><%= link_to("account edit","/main/student_account_edit/#{current_user.id}") %></li>-->
       					       <li><%if session[:teacher]%>
       					       <%= link_to("account edit",edit_teacher_path(current_user)) %>
       					       <%else%>
       					       <%= link_to("account edit",edit_user_path(current_user)) %>
     					       <%end%>
       					       </li>
     						   <li><%= link_to("よくあるお問い合わせ","/main/student_faq") %></li>
     						   <!--id="logout-show"-->
     						   <li><%= link_to("ログアウト","/logout",:method => :delete) %></li>
     						   <!--<li><%= form_tag("/logout") do %>
     						   <%= submit_tag "ログアウト"%>
     						   <% end %></li>-->
   							 </ul>
  						</li>
  						
  						<li><a href="#" ><span class="fa fa-envelope"></a></li>
  						<li><a href="#"><span class="fa fa-bell"></a></li>
  						<li><a href="#"><span class="fa fa-user"></a></li>
  						<!--<li><%= link_to("My page","/main/mypage_student") %></li>----->  
  						
  					    <li><%if is_teacher?%>
  					    <%= link_to current_user.name,"/main/#{current_user.id}/mypage_teacher",class: current_user %>

  					    <%else%>
  					    
  					    <%= link_to current_user.name,"/main/#{current_user.id}/mypage_student"%>
  					    <%end%>
  					    </li>
					</ul>
          	     </div>
            </div>
    <% else %>
        <div class="container">
    		<div class="header-left">
    		   <%= link_to image_tag("https://prog-8.com/images/html/advanced/main_logo.png",:class => 'logo'),
                            {action: 'top', controller: 'users'},{class:'logout'}%>
    		</div>
    		
    		<div class="header-right">
        		<!--<div class="login1" id="login-show">for Student</div>-->
   		       <%= link_to("学生の方へ",root_path,{class:'login1'}) %>

       		</div>
       		
       		<div class="header-right">
        		<!--<a class="login">先生の方へ</a>-->
   		       <%= link_to("先生の方へ",teachers_top_path,{class:'login'}) %>
       		</div>
       		
		

		</div>
       		<!--<div class="header-right">-->
        	<!--	<a class="login">for Student</a>-->
       		<!--</div>	-->

    	</div>
    <% end %>
</header>
		
		
<!--ログアウトモーダル開始------------------------------------------------------>   
<div class="logout-model-wrapper" id="logout-model">
	<div class="model">
		 <div class="close-model">
			<i class="fa fa-2x fa-times"></i>
  	     </div>
  		
  		 <div id="logout-form">
			<h2>ログアウトしますか？</h2>
			<form action="#">
  				<div id="submit-btn1">はい</div>
  				<a id="submit-btn2"  href="#">いいえ</a>
   			 </form>
  		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
		<meta charset="utf-8">
		<title>Ganjin</title>
  
  <%= stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true %> 
  <%= javascript_include_tag 'application' %> 
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	<%= yield :specific_css_js %>
	<%= javascript_include_tag 'navbar' %> 
  <%= csrf_meta_tags %>
  
</head>
<body>
<%= render :partial => "layouts/navbar" %>

<% if flash[:notice] %>
	<header2>
        <div class="flash" id="flash">
            <%= flash[:notice] %>
        </div>
    </header2>
<% end %>
		
<% if @error_message %>
  <header2>
      <div class="form-error">
        <%= @error_message %>
      </div>
  </header2>
<% end %>
<%= yield %>

</body>
</html>